apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app-demo-new
spec:
  selector:
    matchLabels:
      app: movie-app-demo-new
  replicas: 1
  template:
    metadata:
      labels:
        app: movie-app-demo-new
    spec:
      containers:
        - name: movie-app-demo-new
          image: 443576553363.dkr.ecr.us-west-1.amazonaws.com/movie-app-demo
          ports:
            - containerPort: 3000  # Exposing port 3000 in the container
---
apiVersion: v1
kind: Service
metadata:
  name: movie-app-demo-new-service
spec:
  type: LoadBalancer
  selector:
    app: movie-app-demo-new
  ports:
    - name: http
      port: 80           # Expose port 80 for HTTP traffic
      targetPort: 3000    # Map to container port 3000
      protocol: TCP       # Default TCP protocol
