apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app-demo
spec:
  selector:
    matchLabels:
      app: movie-app-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: movie-app-demo
    spec:
      containers:
        - name: react-app
          image: 443576553363.dkr.ecr.us-west-1.amazonaws.com/movie-app-demo
          ports:
            - containerPort: 3000  # Exposing port 3000 in the container
---
apiVersion: v1
kind: Service
metadata:
  name: movie-app-demo-service
spec:
  type: LoadBalancer
  selector:
    app: react-app
  ports:
    - name: http
      port: 3000          # Service port for HTTP
      targetPort: 3000    # Container port
      protocol: TCP        # Explicitly specifying TCP for HTTP
    - name: https
      port: 443           # Service port for HTTPS
      targetPort: 3000    # Assuming your app still listens on port 3000
      protocol: TCP        # Explicitly specifying TCP for HTTPS

